### ISSUE TITLE
Hook for 'catalog' query?

### ISSUE THREAD

**Issue by mvahowe** [unfoldingWord/proskomma-react-hooks#1]
In Chaliki, at startup, there's a query to find out what's in Proskomma, and to display a summary for the user: https://github.com/Proskomma/chaliki/blob/bf11261b8ad738564bd165f825af2047058299ec/src/Pages/Standard/data/Data.js#L16

Would it be possible to have a hook to do this? We should probably add some more fields to make that hook more widely useful.

**Comment by klappy** [comment]
From my understanding Proskomma-freeze is the only way to save and resume state. If that is the case, then separating the importing of state vs documents/docSets seems to help clarify that. Importing (resuming) state will be done in the `useProskomma` because it is picking up where another instance left off. Importing anything other than state should be done via the `useImport` as they are not any Proskomma state representation but something else to be parsed and imported to Proskomma. 

I will keep reviewing the mutation examples to figure out what that custom hook/lifecycle could look like.

**Comment by mvahowe** [comment]
> From my understanding `proskomma-freeze` is the only way to save and resume state.

It should be the easiest way to save and resume "everything". But it's also possible to save and load one docSet at a time (ie all the documents in that docSet as one file) and proskomma-freeze just adds another layer of JSON on top of that docSet-level functionality. So, depending on the granuality of saving, there may be more than one way to do it.

**Comment by mvahowe** [comment]
@klappy I think you are right that thawing something saved using `proskomma-freeze` should happen when Proskomma is instantiated, ie in `useProskomma`. For that to be useful we need a way to freeze the entire state.

**Comment by klappy** [comment]
Refactor for v1 has begun to handle the `useImport` implementation discussed above: https://github.com/unfoldingWord/proskomma-react-hooks/commit/ef117fd283ca92bda6ee15da54da6b4d80bc7758

The following has yet to be implemented:
- documents that aren't usfm, ie. usx
- importing multiple docsets via single json file using proskomma-freeze
- `useImported` to query to see what documents are imported into proskomma

**Comment by klappy** [comment]
Just realizing that `useImported` has the intention to address this issue. In the title, `Hook for 'catalog' query`, catalog is a better term to be used. I'll implement it via `useCatalog` to return the imported docsets.

**Comment by klappy** [comment]
Implemented `useCatalog` here: https://github.com/unfoldingWord/proskomma-react-hooks/pull/5

Remaining sub-issues discussed here should be discussed in other issues:
- importing resumed state via proskomma-freeze: https://github.com/unfoldingWord/proskomma-react-hooks/issues/4
- importing non-usfm files: https://github.com/unfoldingWord/proskomma-react-hooks/issues/3
